/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export class JsToRustStreamString {
  constructor()
  getString(name: string): string
  static fibonacci(n: number): number
}
